services:
  chainlit-qa-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: chainlit-qa-bot
    container_name: chainlit-qa-bot
    environment:
      - USER_ID=test
    ports:
      - "7860:7860"
    volumes:
      - ./local-db:/app/local-db
    depends_on:
      - pgvector
  chainlit-qa-bot1:
    build:
      context: .
      dockerfile: Dockerfile
    image: chainlit-qa-bot
    container_name: chainlit-qa-bot1
    environment:
      - USER_ID=test1
    command: ["chainlit", "run", "cl_app.py", "--host", "0.0.0.0", "--port", "7860", "-h"]
    ports:
      - "7861:7860"
    volumes:
      - ./local-db:/app/local-db1
    depends_on:
      - pgvector
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    volumes:
      - vector-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chat_db
      - POSTGRES_USER=dev_user  # dev only
      - POSTGRES_PASSWORD=1234  # dev only
    ports:
      - "5432:5432"

volumes:
  vector-data: